### ISSUE TITLE
favicon.ico not found

### ISSUE THREAD

**Issue by ckenst** [TestingConferences/testingconferences.github.io#67]
When running jekyll I get an `ERROR `/favicon.ico' not found.` Perhaps we need to add a favicon now?

**Comment by ckenst** [comment]
No longer getting this error message. I think it's been resolved.

**Comment by ckenst** [comment]
Just kidding, it's still there.

**Comment by psabev** [comment]
I think it would be a good idea to create an entire vision - logo, header, fonts, styles... Otherwise favicon alone would look strange. Just on prima vista, I imagine something like that:

![stc-vision](https://user-images.githubusercontent.com/13224010/51747084-0fecfb00-20b1-11e9-83b6-fe3645689750.png)

**Comment by ckenst** [comment]
I have and still would like to hire a designer to help design a better site and build out logos, etc. I have other things I'd like to do first (like get a sponsorship) before I put money into branding updates.
